name: review_that
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  folding_cell:
  path_provider:
  splashscreen:
  firebase_database:
  firebase_core:
  firebase_auth:
  firebase_analytics:
  firebase_messaging:
  flutter_local_notifications:
  shared_preferences:
  connectivity:
  image_picker:
  flutter_rating_bar:
  firebase_storage:
  url_launcher:
  flutter_webview_plugin:
  device_apps:
  background_fetch:
  flutter_facebook_login:
  http:
  flutter_google_places: ^0.2.3
  flutter_places_dialog:
  rxdart:
  geocoder:
  location:
  google_maps_flutter:
  geolocator:
  cached_network_image:
#  gplacespicker: ^0.0.1
#  flutter_share_me:
#  flutter_launch:
#  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  #  when you change the icon please run those in terminal
  #  flutter packages get
  #  flutter packages pub run flutter_launcher_icons:main


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
#    images
    - assets/images/splash_screen_background.jpg
    - assets/images/splash_screen_logo.png
    - assets/images/asian09.png
    - assets/images/backgraound.jpg
    - assets/images/bakery20.png
    - assets/images/beverage07.png
    - assets/images/breakfast08.png
    - assets/images/burger03.png
    - assets/images/categorysq.jpg
    - assets/images/crep10.png
    - assets/images/desert21.png
    - assets/images/fastfood18.png
    - assets/images/grills11.png
    - assets/images/healthy19.png
    - assets/images/indian16.png
    - assets/images/international14.png
    - assets/images/login_logo.png
    - assets/images/mexican13.png
    - assets/images/nuts12.png
    - assets/images/pasta05.png
    - assets/images/pizza04.png
    - assets/images/profile.png
    - assets/images/salad06.png
    - assets/images/seafood17.png
    - assets/images/shawerma02.png
    - assets/images/splash_screen.jpg
    - assets/images/test.jpg
    - assets/images/waffle15.png
    - assets/images/add_new_user.png
    - assets/images/add_new_user2.png
    - assets/images/default_image_category.png


#   icons
    - assets/icons/notification.png
    - assets/icons/share.png
    - assets/icons/cafe.png
    - assets/icons/hospitals_and_clinics.png
    - assets/icons/hotels.png
    - assets/icons/restaurant.png
    - assets/icons/shopping_centers.png
    - assets/icons/stores.png
    - assets/icons/selected_cafe.png
    - assets/icons/selected_hospitals_and_clinics.png
    - assets/icons/selected_hotels.png
    - assets/icons/selected_restaurant.png
    - assets/icons/selected_shopping_centers.png
    - assets/icons/selected_stores.png
    - assets/icons/facebook.png
    - assets/icons/facebook_white.png
    - assets/icons/location.png
    - assets/icons/twitter.png
    - assets/icons/instagram.png
    - assets/icons/uber.png
    - assets/icons/logout.png
    - assets/icons/app_icon.png






  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
