name: esbetalia
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  path_provider:
  splashscreen:
  firebase_database:
  firebase_core:       # This dependency was added during initial configuration.
  firebase_auth:
  firebase_analytics:
  firebase_messaging:
  flutter_local_notifications:
  flutter_plugin_pdf_viewer:
  flutter_full_pdf_viewer:
  open_file:
  url_launcher:
  #  fluttertoast: ^2.2.11


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
#  when you change the icon please run those in terminal
#  flutter packages get
#  flutter packages pub run flutter_launcher_icons:main


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    #images
    - assets/images/logo.png
    - assets/images/schedule_day1.png
    - assets/images/schedule_day2.png
    - assets/images/schedule_day3.png
    - assets/images/games_day1.png
    - assets/images/games_day2.png
    - assets/images/background.png
    - assets/images/back_arrow.png
    - assets/images/splash_screen.jpg
    - assets/images/roheya_day1.png
    - assets/images/roheya_day2.png
    - assets/images/lock.png



    #icons
    - assets/icons/app_icon.png
    - assets/icons/days.png
    - assets/icons/feedback.png
    - assets/icons/games.png
    - assets/icons/logout.png
    - assets/icons/rooms.png
    - assets/icons/teams.png
    - assets/icons/scores.png
    - assets/icons/salah.png
    - assets/icons/roheya.png
    - assets/icons/tranim.png


    #tranem
    - assets/tranem/أنا محتاج لمسة روحك.txt
    - assets/tranem/إحسانك فاق الأوصاف.txt
    - assets/tranem/ادنو اليك.txt
    - assets/tranem/الظلمة لديك.txt
    - assets/tranem/انا اناء اسود.txt
    - assets/tranem/انا شاعر بيك.txt
    - assets/tranem/بعين متحننة.txt
    - assets/tranem/بقدم نفسي ذبيحة.txt
    - assets/tranem/جايين يا ابانا.txt
    - assets/tranem/ربي راعي و سلامي.txt
    - assets/tranem/عارفك مش قادر ترتاح.txt
    - assets/tranem/عايشيين معاك في الهنا.txt
    - assets/tranem/غيرت حياتي.txt
    - assets/tranem/قربني ليك.txt
    - assets/tranem/لسه بتقبلنا.txt
    - assets/tranem/لم تر عين.txt
    - assets/tranem/لما تيجي يا الهنا.txt
    - assets/tranem/لما يسوع بيكون موجود.txt
    - assets/tranem/لمسة شفاء.txt
    - assets/tranem/ليت سلامك.txt
    - assets/tranem/مهما ضعفي امتلكني.txt
    - assets/tranem/هل جلست في هدوء.txt
    - assets/tranem/هيستجيب.txt
    - assets/tranem/وحدك يا يسوع وليس سواك.txt
    - assets/tranem/وفيما اظنه لا يستجيب.txt
    - assets/tranem/يا خالق الأكوان والناس.txt
    - assets/tranem/يا من بحضوره.txt
    - assets/tranem/ياللي عديت الشعب.txt



    #Roheya pdfs
    - assets/Roheya/intro.pdf
    - assets/Roheya/session1.pdf
    - assets/Roheya/session2.pdf
    - assets/Roheya/session2_workshop.pdf
    - assets/Roheya/session3.pdf
    - assets/Roheya/session4.pdf
    - assets/Roheya/salah.pdf

  fonts:
    - family: Adventure
      fonts:
        - asset: fonts/Adventure.otf
    - family: Andalus
      fonts:
        - asset: fonts/Andalus.ttf
    - family: Stylus_Bt
      fonts:
        - asset: fonts/stylu.ttf
    - family: ErasMediumITC
      fonts:
        - asset: fonts/ErasMediumITC.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
